--- #YAML:1.0
name:               excel2csv
version:            1.01
abstract:           dump all worksheets from an Excel file to CSV files
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Getopt::Long:         2.34
    Pod::Usage:           1.16
    Spreadsheet::ParseExcel:  0.55
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
